apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    app: loginwebapp-application
spec:
  replicas: 4
  selector:
    matchLabels:
      name: application-pod
      app: loginwebapp-application
  template:
    metadata:
      name: application
      labels:
        name: application-pod
        app: loginwebapp-application
    spec:
      containers:
      - name: login-app
        image: adarshnagaraj22/loginapplication:1.0
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
