apiVersion: v1
kind: Service
metadata:
  name: application-service
  labels:
    name: login-app-service
    app: loginwebapp-application
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: application-pod
    app: loginwebapp-application
