apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql-service
    app: loginwebapp-application
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysql-pod
    app: loginwebapp-application
